apiVersion: v1
kind: Pod
metadata:
  name: private-reg
  labels:
    app: private-flask
spec:
  containers:
    - name: private-flask-test
      image: docker.io/mattfeng/private-flask-test:latest
      ports:
        - containerPort: 8000
          name: http-web-svc
  imagePullSecrets:
    - name: regcred
