apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
    - name: private-flask-test
      image: docker.io/mattfeng/private-flask-test:latest
  imagePullSecrets:
    - name: regcred
